### ISSUE TITLE
"tmux" does not work inside container

### ISSUE THREAD

**Issue by bitc** [tailhook/vagga#118]
I created an Ubuntu container with [tmux](https://tmux.github.io/) installed (using the regular Ubuntu package).

But it doesn't work:

    $ vagga _run build tmux
    create session failed: : Permission denied

Another attempt fails with no output:

    $ vagga _run build bash
    # tmux
    #

I also tried [GNU Screen](https://www.gnu.org/software/screen/), and it similarly fails to run.

**Comment by tailhook** [comment]
Well, I've implemented support of pseudo-tty. But tmux doesn't work, because it needs to control output tty which is not in the container. I'm not sure how to fix it.

It may be fixed by creatinig pseudo-tty inside the container and proxying, but I'm not sure if it worth it. BTW, currently you can run tmux with `python -c 'import pty; pty.spawn("tmux")'` :)

**Comment by bitc** [comment]
Thanks. I compiled latest version of vagga from git master, and then I was able to run tmux using the python pty trick you wrote.

But the size of the resulting tmux terminal is fixed at 80x24, rather than filling up the entire xterm window. For now, I am able to manage with this though.

**Comment by tailhook** [comment]
Well, everything left, is more issue of how tmux discovers it's controlling tty, rather than something vagga can fix. So I'm closing this issue for now.
