### ISSUE TITLE
X/GUI support

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#132]
It would probably be nice to have `--allow-x11` command-line flag and setting which could work without any additional setup. While it could work now (see #126) there are couple of issues:

1. A volume must be defined both in settings and in container
2. Graphic drivers might need to be installed

While (1) is just inconvenience, (2) comes seriouly against the vagga's philosophy of "configure once, run everywhere".

(1) can be fixed easily by making a shortcut which adds the volume
(2) needs more serious work:

a. Detecting video driver (where detection method depends on host system, but installation target depends on guest system)
b. Allowing to customize it somehow

While (a) is a great convenience, it will never work for all cases. On the contrary (b) can work for everyone, but require a little bit preparation work (but the work may be reusable across the project).
 
Probably it can be done with something like:

```
  setup:
  - !Ubuntu trusty
  - !Install [firefox]
  - !CustomInstall video-driver-ubuntu-trusty
```
And the settings file which has something along the lines of:
```
custom-installs:
  video-driver-ubuntu-trusty:
  - !Install [xserver-xorg-video-intel]
```

Related issues #126, #131

**Comment by popravich** [comment]
Hi, under Ubuntu 15.04 (XUbuntu and lightdm) there is an issue with firefox and chromium:
```$ firefox
no protocol specified
cannot open display: :0.0
```
It requires `~/.Xauthority` to be accessible in container.
However, this only solved the issue for firefox, chromium still fails to start

**Comment by lilianmoraru** [comment]
@popravich While I don't have the solution, I have a suggestion.
This is not a vagga specific issue. When I know that it is a container issue(that you run the command/software/... in the container), I usually search the same issue related to docker since docker has been in the wild for a long time and you can find more info about docker related issues.
Here, I searched on Google for "docker display 0.0" and this is my first result: http://stackoverflow.com/questions/28392949/running-chromium-inside-docker-gtk-cannot-open-display-0

**Comment by tailhook** [comment]
Well, we have few working examples already. I think this issue doesn't need any more attention.
