### ISSUE TITLE
Add possibility to share a directory other than the working directory with the container

### ISSUE THREAD

**Issue by parhamdoustdar** [tailhook/vagga#201]
Currently, the only directory shared between the host machine and the container is the directory `vagga.yaml` resides in (known as `/work` inside the container). It would be useful to be able to share another directory with the container in the form of volumes. For example, maybe allow a prefix that makes vagga know that the directory is outside the container and in the host machine.

This has a few use cases:

* It could help with making vagga cross-platform: applications that create symlinks in directories (such as `postgresql` in its `data` directory) can be installed on vagrant machines running on Windows.
* It could help with people not wanting to litter the `/work` directory with artifacts such as logs. This would mean that you wouldn't have to have a `logs` directory in your repository with a `.gitignore` with something like this inside:

```
*
!.gitignore
```

Not sure if this idea is worth it, but putting it here since this is blocking me from installing `postgresql` in a vagga container on an Ubuntu virtual machine created by vagrant.

**Comment by lilianmoraru** [comment]
@parhamdoustdar Let me know if I didn't understand this correctly.
Vagga already supports this. What you need to do is:
- Add the [external volumes](http://vagga.readthedocs.org/en/latest/settings.html?highlight=external%20volumes#opt-external-volumes) your are interested in the [global settings](http://vagga.readthedocs.org/en/latest/settings.html#global-settings):
```yaml
external-volumes:
  Path:  /path/on/host
```

- In your `vagga.yaml` create the directory where you want to mount this volume:
```yaml
- !EnsureDir /Path
```

- Mount the external volume to your directory inside the container:
```yaml
volumes:
      /Path:   !BindRW /volumes/Path
```

**Comment by parhamdoustdar** [comment]
Ah, yes, I forgot to note my issue with this approach. Thanks for the reminder!

My issue with this is that this means everyone who checks out your project *must* have a location defined in their global settings. Since as far as I know vagga is going for `git clone <url> && vagga run`, this adds extra steps.

What I'm proposing is the ability to add a volume in `vagga.yaml` that will be defined as an external volume, and then will be used, so that everyone wouldn't have to go and define it for themselves.

Am I understanding the issue right, or am I getting things wrong here? i haven't tried the external volumes feature, I have just read about it.

**Comment by tailhook** [comment]
@parhamdoustdar this is a the security measure. The program that is running in vagga can't escape its project dir, or volumes defined in settings.

It's also not entirely clear why would you need that. I.e. you either need  project-specific data (and you can put that in `/work`) or you have some well-known location like `/etc/.X11-unix`. There might be some exceptions, for example if you have multiple projects in a company with different vagga files, you might say that every employee must declare `volumes: { mycompany: /home/myuser/mycompany }` and then any vagga.yaml can use some subfolder of `/volumes/mycompany`. So you have to set it up once, but not for every project.

For use case defined in the start of this ticket, we could probably allow using `!BindRW` for subfolders of `projectdir/.vagga`. Because you have already set up `.vagga` to handle symlinks and hard links anyway. But to do that we must better define the lifecycle of the volume. Like when they are going to be created and deleted, what if volume is removed from config and added back again, and how they behave then `storage-dir` is configured.

If you can come up with good spec for the volumes inside the `.vagga`, it's easy to implement.

**Comment by lilianmoraru** [comment]
@parhamdoustdar What I do is actually more like this: `git clone <url> && ./setup_vagga.sh && vagga run`

@tailhook I never told you but I actually don't like one limitation that comes with `Global Settings`.
When I first tried to use `external-volumes`, I've put paths that look something like this: `${WorkArea}/Folder` and it complains that you need to use absolute paths.
In the environment I did that, every developer has different paths to their work area, so I was forced to create a configure script that has to be run by every developer separately every time they make a copy of the project, instead of having 1 general `Global Settings`(that is copied once) that every developer can use by default.

So, there are some limitations with the current setup, although one can work around them.

**Comment by tailhook** [comment]
@lilianmoraru what is WorkArea? I think we can expand some things in ~/.vagga.yaml like `~` or even environment variables. But we can't allow mount arbitrary directory by default.

**Comment by parhamdoustdar** [comment]
I think subdirectories of /work/.vagga are a perfect middleground. I 
agree that we need to find a better life cycle for them though. Maybe 
just create the directory the first time the build step is encountered 
and let the user handle cleaning or removing it using other build steps, 
and remove it when `_clean --everything` is implemented?

**Comment by lilianmoraru** [comment]
@tailhook It's an environment variable that points to the work area(project) the developer is working on currently. I haven't tested lately but I think even using `$HOME` won't work.

**Comment by tailhook** [comment]
@lilianmoraru, well, we expand tilde `~` in `storage-dir` and `cache-dir` but not in volumes. Certainly we can fix that. But I'm a little bit sceptical about expanding arbitrary environment variables. For example, I'm not sure why adding `WorkArea` environment variable (to your `bashrc` or whatever startup script) is easier than adding a line to `vagga.yaml`.

@parhamdoustdar `vagga _clean --everything` is just a synonymous to `rm -rf .vagga`, with proper permissions (just FYI).

(not answering other points, I have to think about temporary/magical/hidden volumes a bit more)

**Comment by tailhook** [comment]
Just another thought: for vagrant it's fine to allow mount everything. So your `Vagrantfile` and vaggrant-vagga may put default vagga settings with `volumes: { host-system: / }` or something similar.

**Comment by tailhook** [comment]
Okay, you can take a look at #204

**Comment by tailhook** [comment]
Okay, I think this issue will be exhausted when we implement #204.
