### ISSUE TITLE
Improve Performance for running commands

### ISSUE THREAD

**Issue by bitc** [tailhook/vagga#22]
$ time vagga _run dev true

    real    0m0.188s
    user    0m0.061s
    sys     0m0.031s

180 milliseconds doesn't seem like much of an overhead when performing large builds. But it's a noticeable annoyance for editor plugins that do real time syntax checking, linting, etc..

**Comment by cablehead** [comment]
Just out of interest, which base OS are you using? I find alpine environments to be dramatically faster than ubuntu ones.

**Comment by tailhook** [comment]
Well, on my unscientific tests there is no difference between alpine and ubuntu containers, when container is run.

I have about 220 ms time when running unoptimized vagga. About 140 ms when vagga is built with `RUSTC="rustc -C opt-level=3"`. And about 66 ms when I comment out vagga version check.

I need to profile more thoughtfully. But anyway I have two questions:

1. Do you think running `vagga --no-version-check` is ok for syntax checking? (i.e. container will be rebuilt next time you'll run real app not syntax checker) I think it's good, because it's unpleasant if syntax checker try to rebuild container, especially when vagga.yaml depends on file being edited.

2. What's the reasonable goal? 16 ms? (i.e. time for single frame for 60 fps output)

Otherwise I find this use case very promising for vagga.

**Comment by bitc** [comment]
I'm running Ubuntu both as my main OS and container.

1. Yes, a `--no-version-check` flag would be great!

2. 16 ms would be amazing, but for my uses even 50 ms would feel smooth enough.

Thanks for all the work on vagga, it's a really cool project

**Comment by tailhook** [comment]
Sorry for long delay. I've finally got it working:
```
  $ time vagga --no-version-check _run docs true
  vagga --no-version-check _run docs true  0.01s user 0.01s system 20% cpu 0.072 total
  $ time vagga --no-version-check _run rust-musl true
  vagga --no-version-check _run rust-musl true  0.01s user 0.01s system 21% cpu 0.051 total
```
Is it well enough for you? This is optimized build (vagga-testing repos have an unoptimized build for simpler backtraces). Unoptimized build gives 150-180 ms on my laptop.

**Comment by tailhook** [comment]
BTW, @bitc, could you briefly describe your setup. Like which editor you use and how do you setup it.

Ideally I want to setup some conventions for vagga so that you can jump between projects and have all the checks and lints work on a per-project basis.

**Comment by tailhook** [comment]
Okay, I believe it's good enough. Feel free to reopen the bug if it isn't.
