### ISSUE TITLE
Wrong storage-dir change error

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#244]
In `$HOME/.vagga/settings.yaml` I had these:
```yaml
storage-dir: /home/lilian/.vagga/
cache-dir: /home/lilian/.vagga/.cache
```

I've than built a container after which I decided to change the `settings.yaml` to put the `storage-dir` in a separate folder, so I changed to:
```yaml
storage-dir: /home/lilian/.vagga/image-storage
cache-dir: /home/lilian/.vagga/vagga-cache
```

I removed all the containers from `$HOME/.vagga`.
Of course the `.vagga/.lnk` is now pointing to a non-existent container + the `storage-dir` changed.
It gives this error:
```
ERROR:vagga::wrapper: Error executing _build: You have set storage_dir to {}, but .vagga/.lnk points to {}. You probably need to run `ln -sfn {} .vagga/.lnk`
```

The issue is `{}` but I think it could also suggest to remove the local `.vagga` with a warning on what that means(rebuild). Although the suggestion is better than removing `.vagga`. Removing is viable only if the container was removed.

**Comment by tailhook** [comment]
Fixed error message in 4a509a0, it's a little bit more smart now.

>  it could also suggest to remove the local .vagga with a warning on what that means(rebuild). Although the suggestion is better than removing .vagga. Removing is viable only if the container was removed.

The reason I suggest relinking is because if you just moved storage-dir, but not start with a clean one, you will get `project` directory kept around and `project-1` started with for new `.vagga` directory.

Anyway, let me know whether the new message logic is good enough.
