### ISSUE TITLE
Compatiblitity with Docker (and Vagrant)

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#25]
The README says:

> Compatibility with Vagrant-LXC and Docker

but the docs only make reference to [docker2vagga.py](https://github.com/tailhook/vagga/blob/master/tests/subconfig/docker2vagga.py), so I ask, there's posibility to do it the other way? This could make vagga some kind of "lingua franca", so I could be able to publish vagga images and they could be converted to Docker too... I could do it the other way, but I would like to take advantage of vagga feature about not needed sudo permissions by default :-)

**Comment by tailhook** [comment]
The problem is two-fold:

1. Vagga uses same system calls which docker and vagrant lxc uses. So might use same binaries (images) for containers.

2. Reusing build/download process (i.e. Dockerfile)

First statement means, you can do `docker export` and unpack that tar to container (e.g using Tar command, but I've not tested it in vagga 0.2.x, in 0.1.x it worked perfectly, let me know if it doesn't work). Similarly you should be able to use `!TarDownload` to directly download vagrant-lxc image and run container from it.

It works other way too: you can build image with vagga and then use `docker import`

Reusing build tools/process is much more complex task. I think we don't want to support lxc templates, they are complex, and there are a lot of hacks in bash. So that it's easier to build image with lxc, or to embed needed lxc templates' features into vagga itself.

Dockerfiles are not easy too. The problem is that docker heavily relies on image caching. Without that building images is too slow. Caching images is almost impossible to implement for unprivileged user (honestly its also too slow in docker). So vagga relies on caching of downloads (and will try to cache build artifacts in future). To make this work, vagga needs to understand specific package manager used. Understanding commands is hard for Dockerfile, which is basically a list of lines of bash, with some metadata attached.

So for limited cases docker2vagga.py approach works (but it's not in stable version yet). But I'm not sure what would be good for generic case. The docker2vagga produces either config which is slow to (re)build or the one which doesn't work for all Dockerfiles.

That's the summary. I'm open to any ideas.

**Comment by piranna** [comment]
> It works other way too: you can build image with vagga and then use docker import

Oh, that's cool! So you can build a vagga image and later use it on docker with 'docker import'? That's just what I was asking for, good to know it's so easy! :-D

From your answer seems you understood I was asking about vagga being able to control both vagga, docker and vagrant environtment (and I must to admit my message was confuse at this point), but although it would be a good thing, probably a difficult task too and also something that would be better done by an external project, something like a "containers manager" that can understand and execute commands of the different container systems instead of doing itself.

**Comment by tailhook** [comment]
> Oh, that's cool! So you can build a vagga image and later use it on docker with 'docker import'?

Right. I've done that before. There was a bug in docker handling of symlinks for few edge cases, but I believe it's fixed in recent versions (bug could be avoided by using Dockerfile ``ADD .`` instead of ``docker import``)

> From your answer seems you understood I was asking about vagga being able to control both vagga, docker and vagrant environtment

This is absolutely out of scope for vagga. I guess someone may do a vagrant plugin for vagga (there is one for docker). I.e. vagrant is more suited for managing heterogeneous environments. But this mostly defeats all the features of vagga (i.e. light weight, no init/ssh, monitoring multiple processes)

**Comment by piranna** [comment]
> Right. I've done that before. There was a bug in docker handling of symlinks for few edge cases, but I believe it's fixed in recent versions (bug could be avoided by using Dockerfile ADD . instead of docker import)

Cool! Then this can be clossed :-) Maybe you could put a note about this on the readme :-)


> This is absolutely out of scope for vagga. I guess someone may do a vagrant plugin for vagga (there is one for docker). I.e. vagrant is more suited for managing heterogeneous environments. But this mostly defeats all the features of vagga (i.e. light weight, no init/ssh, monitoring multiple processes)

That's why I talk later about a "containers manager" on top of them... ;-)
