### ISSUE TITLE
Ability to use !Supervise and specify processes start order

### ISSUE THREAD

**Issue by lud4ik** [tailhook/vagga#28]
If I have a case that I want to supervise several commads, but some of them need another to be already started. In current docs it's said that they are started simultaneously.
What is current the solution? To use separate supervise sections or commands?

**Comment by tailhook** [comment]
Well, can you describe your use case with more detail?

The problem is that just specifying the order doesn't solve anything. Because processes will be started with (I believe) a fraction of millisecond between them. Presumably not giving a time to create files or bind sockets before starting next process.

Current decent way to handling dependencies is to allow processes to wait and reconnect themselves. I.e. if your process needs a DB to connect to. It must try to connect immediately, if it's not successful wait a fraction of second and connect again. I.e. it must handle reconnection anyway, because in real production circumstances DB may be unavailable at any time.

The latter is true if you are developing server-side software (which I use vagga for 99% of the time). For other use cases YMMV.

**Comment by lud4ik** [comment]
Feel you are right, it's better to rewrite to handle reconnection even for systems that must be high available:)

**Comment by lud4ik** [comment]
What is the right approach to handle when one microservice at start call APIs (because to work it needs data that is managed in second) from another and if second don't work, first fails; should it do all calls with retrying? Or is smth else wrong?

**Comment by rrader** [comment]
@lud4ik look at this example https://github.com/tailhook/vagga/blob/master/examples/postgres-alembic/vagga.yaml
I was trying to solve same problem, command "service" waits while postgres will start and create the database.

**Comment by tailhook** [comment]
@rrader that is okay for command-line utils like alembic. But for services the better approach is to keep retrying.

@lud4ik, your network may fail in production too, right? If you decide that your service should die if network fails (like mesos do) then yes, you might want to have external script that does the work. Example might be `while ! curl http://locahost:12345 > /dev/null; sleep 0.1; done; run command`.
