### ISSUE TITLE
Some examples for relational dbs setup 

### ISSUE THREAD

**Issue by lud4ik** [tailhook/vagga#36]
mysql for example?

**Comment by lud4ik** [comment]
```
After execute None (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```
I want to connect from container to local mysql.
Do I have to create link for sock?

**Comment by tailhook** [comment]
No, just connect as usual.

**Comment by tailhook** [comment]
Ah, sorry, if you want to use unix sockets, you must make the socket directory visible somehow.

So the easier solution is to use TCP socket. I.e. remove "skip-networking" from mysql config ("my.cnf") and use "127.0.0.1" instead "localhost" for address.

But if you still want unix-sockets, the setup is a bit more complex. Because vagga intentionally isolates filesystem for security you have two options:

1. You can bind-mount folder inside project folder, for example:
```
sudo mount --bind /var/run/mysqld ./tmp/mysqld
```
Then you can either bind mount it in place inside the container:
```
volumes:
  /var/run/mysqld: !BindRW /work/tmp/mysqld
```
or you can just point the client to use `/work/tmp/mysqld/mysqld.sock`

2. You can configure external mysqld server to put file inside your home directory:
```
mysqld --with-unix-socket-path=/home/user/projects/myproject/tmp/mysqld.sock
```
(or just edit my.cnf) And set path to `/work/tmp/mysqld.sock` in the client

**Comment by lud4ik** [comment]
Thanks!

**Comment by lud4ik** [comment]
I don't really understand why I have problem even if I comment bind-adress (mysql 5.6)
```
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
# bind-address		= 127.0.0.1

```
Err
```
2003, "Can't connect to MySQL server on '127.0.0.1' (111)")
```
I' ve restarted mysql service.
Maybe connections are blocked someway another way?

**Comment by lud4ik** [comment]
but maybe it's the problem of MySQL-python==1.2.5...

**Comment by tailhook** [comment]
You should probably uncomment bind-address. And you may want to look at ss:
```
> sudo ss -nlp | grep mysql
tcp    LISTEN     0      100    127.0.0.1:3306                 *:*                   users:(("mysql",pid=4615,fd=27))
```
