### ISSUE TITLE
Upload vagga to crates.io

### ISSUE THREAD

**Issue by labdsf** [tailhook/vagga#392]
Make it possible to install vagga with `cargo install vagga`.

**Comment by tailhook** [comment]
Well, vagga now ships with busybox, apk, and alpine-keys, which need to be downloaded/installed with vagga. As far as I know there is no such mechanism in cargo install. I.e. cargo install is only suited to install a single binary.

**Comment by tailhook** [comment]
And also you need to build vagga with musl libc. I'm not sure cargo install support that, but it's definitely not a default. So users will get defunct vagga by default (vagga doesn't work with dynamic linking because we need to run vagga in container where there are no original dynamic libraries such as libc).
