### ISSUE TITLE
work directory?

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#97]
I've found that vagga adds a `work` directory that bind to the project directory on the host machine. I has two questions related to it:

* since it's not a directory of the filesystem itself but instead is being added by vagga, why it's not hidden like docker `.dockerinit` file (and the same happens with the `run` directory)? Also it could have some vagga-something name so it's easier to identify (both that are vagga related files and also that we are running on a vagga or a LXC environment...)
* when exec `vagga run` I get thrown directly to that directory instead of the root filesystem, that's the default `$HOME` environment variable for linux kernel and also what Docker does. I understand that it could make sense for the use case where you want to exec your current project folder inside a LXC container, but what about when you have everything ready on tarballs? How are you able to have `$HOME` set to `/` (and if possible, no `/work` directory mounted)?

**Comment by tailhook** [comment]
> since it's not a directory of the filesystem itself but instead is being added by vagga, why it's not hidden like docker .dockerinit file (and the same happens with the run directory)? Also it could have some vagga-something name so it's easier to identify (both that are vagga related files and also that we are running on a vagga or a LXC environment...)

Because you want to use it everywhere in paths, settings, `cd /work` and so on. The `/.work` would look ugly. It's not `/vagga-work` because I hate `/vagrant` directory, it would be much nicer if both vagrant and vagga use same mount point for project directory.

>  (and the same happens with the run directory)

Well `/run` is very used directory in every linux distribution known to me (it's also there `/dev/shm` points in some distributions to make shared memory work). It's there to create less problems, just like `/tmp`, `/proc` and similar. You can change parameters of `/run` mountpoint by adding it to `volumes`. But I'm not sure you can cancel it. Probably `volumes: { /run: null }` should be
used for that (but I'm almost sure it doesn't work at the moment).

> How are you able to have $HOME set to / (and if possible, no /work directory mounted)?

Home is set just like any environment variable:

* http://vagga.readthedocs.org/en/latest/container_params.html#opt-environ
* http://vagga.readthedocs.org/en/latest/commands.html#opt-environ

Note: some programs read `/etc/passwd` instead of HOME (Java, all setuid programs ...). You can write anything to `/etc/passwd` too.

> when exec vagga run I get thrown directly to that directory instead of the root filesystem

Because it's the most useful thing to do, for development environments. There is http://vagga.readthedocs.org/en/latest/commands.html#opt-work-dir and `work-dir: /` works well.

> (and if possible, no /work directory mounted)?

The `/work` is just sane default. Convention over configuration. I don't have a clear use case to have no `/work` mounted. Usually even if it is not used it's not harmful.

We could add `/work` as a special volume type (just like `!VaggaBin`) and allow to disable it as described above.

If you can suggest improvements to documentation, please do a pull request:)

**Comment by tailhook** [comment]
I don't think there is anything actionable here left.
